### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by kadirnar** [yjh0410/FreeYOLO#3]

**Comment by yjh0410** [comment]
@kadirnar Sorry, there is no paper about my FreeYOLO. FreeYOLO just draws some ideas from YOLOv4 (Mosaic augmentation), YOLOX(SimOTA and loss function) and YOLOv7(ELAN-backbone and ELAN-PaFPN).

**Comment by kadirnar** [comment]
No problem. I was curious about the changes you made in architecture. Thank you very much for your reply. You do very good projects. Congratulations
